In [1]:
# To enable plotting graphs in Jupyter notebook. 
# This should always be the first step before importing the other libraries
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
from scipy.stats import zscore
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
import seaborn as sns

In [4]:
import os
os.chdir('C:/Users/ASHISH/Desktop/CLASSIFICATION-SUPERVISED LEARNING')

In [68]:
data1 = pd.read_csv("train_1.csv")
data2 = pd.read_csv('test.csv')

In [69]:
data1

       Ref.No      X1  X2  X3  X4  X5  X6  X7  Y
0       22203  320000   2   1   2  27   1   2  1
1        1288  470000   1   2   1  41  -2  -2  0
2       11822   20000   1   2   2  25   1   2  0
3       15085   80000   1   3   1  41   0   0  1
4        6192   30000   1   1   2  30   1  -2  1
5       12894  320000   2   2   1  39   0   0  0
6        2279   50000   2   3   1  37   2   0  1
7        1282  360000   1   1   2  34   1  -2  0
8       13334   50000   2   1   1  25   0   0  0
9       15251   30000   2   2   1  45   2   0  0
10      12165  130000   2   3   1  41   0   0  0
11       9895  270000   2   2   1  42   0   0  0
12      18930  200000   2   1   1  30  -2  -2  0
13      16828  150000   1   1   1  43  -2  -2  0
14      16492   50000   1   2   2  22   0   0  0
15       3785   30000   1   1   2  32   0   0  0
16      14665   30000   2   2   2  23   0   0  0
17      18146  260000   1   2   2  31   0   0  0
18       4376   60000   1   3   1  31   1   2  1
19      17544   20000   2   2   1  40   0   0  0
20      18421   40000   2   2   2  24   2   0  1
21      23940   50000   1   2   2  27   1   2  1
22       1273  370000   2   1   1  53  -1  -1  0
23       4811  300000   2   1   2  31   0   0  0
24       8334  360000   1   1   1  44   0   0  0
25      15711  270000   1   1   1  45   1  -1  0
26      16811  140000   1   3   1  38   0   0  0
27      13816  130000   1   1   2  43   0   0  0
28      20565   50000   1   3   2  25   0   0  0
29       9594   20000   2   1   2  26   2   2  1
...       ...     ...  ..  ..  ..  ..  ..  .. ..
21570   20745  450000   1   1   1  45  -1  -1  1
21571    4885   70000   1   2   2  30   0   0  1
21572    7208  200000   2   2   1  44  -1   2  0
21573   17977  120000   1   2   1  45   0   0  0
21574   19881  200000   2   2   2  36   0   0  1
21575   19480   50000   2   3   2  35   0   0  0
21576   12381  210000   2   1   2  27   0   0  0
21577    2342  140000   2   3   2  33   1  -2  0
21578   12838  150000   2   2   2  23   0   0  0
21579   18953   70000   2   1   2  26   0   0  0
21580   14238  500000   1   1   2  41  -1  -1  1
21581    7306   50000   1   2   3  51   0   0  0
21582   11652  130000   2   1   2  30   1  -2  0
21583    3637   50000   1   3   2  30   0   0  0
21584    2308   30000   2   1   2  30   1  -2  0
21585    3224   30000   2   2   2  28  -1  -1  1
21586   22787  100000   2   3   1  40   2   2  1
21587   17130   80000   2   2   2  24   2   2  1
21588    4029   60000   2   2   2  27   0   0  0
21589   23408  360000   2   2   2  35   1  -2  0
21590    4380  210000   2   1   1  42   1  -2  0
21591   18482   50000   2   1   1  25   0   0  1
21592   23587  240000   2   2   1  40  -1  -1  1
21593   14040   30000   2   2   2  24  -1  -1  0
21594   20290  210000   2   1   1  51  -1  -1  0
21595    7650  150000   1   2   1  39  -1  -1  0
21596   15207   70000   2   3   2  29   0  -1  0
21597    5471  140000   1   2   2  27   0   0  0
21598    6855  180000   1   1   1  35   1   2  1
21599    2673   30000   2   2   2  41   0  -1  0

[21600 rows x 9 columns]

In [50]:
data2

      Ref.No      X1  X2  X3  X4  X5  X6  X7
0      17083   50000   2   1   2  25   0   0
1       3494  120000   2   2   2  24   0   0
2      21945  120000   2   2   2  27   1  -2
3       3499   60000   1   1   2  28   0  -1
4      18973  100000   2   1   2  28   3   2
5       3249  290000   2   2   1  34   0   0
6      22537  130000   2   2   1  48   2   2
7       9577   20000   1   2   1  40   1   2
8       3699  360000   1   2   2  28   1  -2
9      19542  170000   2   1   1  38  -1  -1
10     15567   50000   1   3   2  40   0   0
11      1962  130000   2   3   2  53  -1  -1
12     20610  130000   1   2   2  29   2   2
13     22458   50000   2   3   1  49   0   0
14      8683   50000   2   2   2  24   2   2
15     23712  290000   2   2   1  52   0   0
16      2157  290000   2   1   2  25   0   0
17     17319  120000   2   2   2  25   2   3
18     16160  110000   2   2   2  39   0   0
19      9695   20000   1   3   2  23   2   2
20     14170  300000   1   1   1  40  -1   2
21      6094   20000   1   1   2  24  -1  -1
22     17252   20000   2   3   1  37   1   2
23     15781  130000   2   1   2  27   0   0
24      4022  270000   2   2   2  31  -2  -2
25      7509   10000   2   3   2  51   0   0
26     19192   50000   2   2   1  38   0   0
27     21093  260000   1   5   1  42   0   0
28      9234  140000   1   3   2  30   2   2
29      9199  260000   1   2   1  31   0   0
...      ...     ...  ..  ..  ..  ..  ..  ..
2369    1136   60000   2   2   2  31   0   0
2370   19440  300000   2   2   1  35   0   0
2371   19329  140000   2   3   1  40   2   0
2372    4417  270000   2   3   1  37   1  -1
2373    8480  160000   1   2   2  37   1  -2
2374   16592   80000   1   3   1  31   1   2
2375   10389   10000   1   2   2  22   0   0
2376    3460  230000   1   2   2  30   0   0
2377   12833  110000   1   1   2  26   0   0
2378   17796  470000   2   2   1  54   1   2
2379    9860  200000   2   1   1  28  -1  -1
2380   15638   80000   2   2   2  26   0   0
2381   19874  500000   2   2   1  46   0   0
2382   13735   60000   2   2   1  46   0   0
2383    6811   10000   1   1   2  30   0   0
2384   21393  150000   1   1   1  54   1   2
2385   19591   80000   2   2   2  36   0   0
2386   12408  270000   2   1   1  33   0   0
2387   11468   20000   1   3   1  45  -1   2
2388    1810  500000   2   1   2  46  -2  -1
2389   12288  200000   1   1   1  40  -1  -1
2390   21128  500000   1   1   1  41  -1  -1
2391      28   50000   2   3   2  30   0   0
2392   10518  280000   2   3   1  37  -1  -1
2393    7060   50000   2   2   3  30   2   2
2394   14580  140000   2   2   1  34   0   0
2395    5172   70000   1   3   1  46   2   2
2396    3598   50000   2   2   1  37   2   2
2397   18841  190000   2   2   2  27   2   2
2398   21365   70000   1   2   1  54  -1   0

[2399 rows x 8 columns]

In [51]:
data1.shape

(21600, 9)

In [70]:
data2.shape

(2399, 25)

In [112]:
data_test = data2.iloc[:,0:8].values

In [113]:
data_test

array([[ 17083,  50000,      2, ...,     25,      0,      0],
       [  3494, 120000,      2, ...,     24,      0,      0],
       [ 21945, 120000,      2, ...,     27,      1,     -2],
       ...,
       [  3598,  50000,      2, ...,     37,      2,      2],
       [ 18841, 190000,      2, ...,     27,      2,      2],
       [ 21365,  70000,      1, ...,     54,     -1,      0]], dtype=int64)

In [71]:
data1.dtypes

Ref.No    int64
X1        int64
X2        int64
X3        int64
X4        int64
X5        int64
X6        int64
X7        int64
Y         int64
dtype: object

In [72]:
data2.dtypes

Ref.No      int64
X1          int64
X2          int64
X3          int64
X4          int64
X5          int64
X6          int64
X7          int64
X8          int64
X9          int64
X10         int64
X11         int64
X12         int64
X13         int64
X14         int64
X15         int64
X16         int64
X17         int64
X18         int64
X19         int64
X20         int64
X21         int64
X22         int64
X23         int64
Y         float64
dtype: object

In [73]:
data1.head(5)

   Ref.No      X1  X2  X3  X4  X5  X6  X7  Y
0   22203  320000   2   1   2  27   1   2  1
1    1288  470000   1   2   1  41  -2  -2  0
2   11822   20000   1   2   2  25   1   2  0
3   15085   80000   1   3   1  41   0   0  1
4    6192   30000   1   1   2  30   1  -2  1

In [74]:
data2.head(5)

,Ref.No,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,17083,50000,2,1,2,25,0,0,0,0,...,38008,31898,20154,2000,5040,8034,3029,5000,49436,NaN
1,3494,120000,2,2,2,24,0,0,0,0,...,6761,7189,1087,1400,1000,0,1000,1087,801,NaN
2,21945,120000,2,2,2,27,1,-2,-1,-1,...,0,0,0,0,2382,0,0,0,0,NaN
3,3499,60000,1,1,2,28,0,-1,0,0,...,9900,310,160,6000,10000,900,310,0,3400,NaN
4,18973,100000,2,1,2,28,3,2,0,0,...,53407,51951,53195,0,1831,4339,0,2083,1939,NaN

In [75]:
data1.describe().T

,count,mean,std,min,25%,50%,75%,max
Ref.No,21600.0,12000.773750,6931.541584,1.0,6008.75,12001.5,17995.25,24000.0
X1,21600.0,165235.818519,129013.755215,10000.0,50000.00,140000.0,230000.00,1000000.0
X2,21600.0,1.626991,0.483616,1.0,1.00,2.0,2.00,2.0
X3,21600.0,1.845926,0.781139,0.0,1.00,2.0,2.00,6.0
X4,21600.0,1.558704,0.522008,0.0,1.00,2.0,2.00,3.0
X5,21600.0,35.382361,9.266769,21.0,28.00,34.0,41.00,79.0
X6,21600.0,-0.002917,1.126164,-2.0,-1.00,0.0,0.00,8.0
X7,21600.0,-0.124028,1.201892,-2.0,-1.00,0.0,0.00,8.0
Y,21600.0,0.223796,0.416797,0.0,0.00,0.0,0.00,1.0

In [76]:
data2.describe().T

,count,mean,std,min,25%,50%,75%,max
Ref.No,2399.0,11995.526469,6901.316680,28.0,5929.0,11993.0,18040.0,23998.0
X1,2399.0,167886.619425,130167.636127,10000.0,50000.0,140000.0,240000.0,750000.0
X2,2399.0,1.639850,0.480144,1.0,1.0,2.0,2.0,2.0
X3,2399.0,1.861192,0.769730,0.0,1.0,2.0,2.0,6.0
X4,2399.0,1.543977,0.522676,0.0,1.0,2.0,2.0,3.0
X5,2399.0,35.363902,9.313315,21.0,28.0,34.0,41.0,71.0
X6,2399.0,-0.005419,1.098739,-2.0,-1.0,0.0,0.0,6.0
X7,2399.0,-0.117966,1.188564,-2.0,-1.0,0.0,0.0,6.0
X8,2399.0,-0.132138,1.204854,-2.0,-1.0,0.0,0.0,7.0
X9,2399.0,-0.187995,1.174907,-2.0,-1.0,0.0,0.0,7.0
X10,2399.0,-0.242184,1.130053,-2.0,-1.0,0.0,0.0,7.0
X11,2399.0,-0.258024,1.159737,-2.0,-1.0,0.0,0.0,7.0
X12,2399.0,52545.473114,73347.084426,-14386.0,3629.0,23570.0,71745.0,533142.0
X13,2399.0,51489.033347,72077.269174,-13543.0,2999.0,23242.0,69689.0,524555.0
X14,2399.0,48981.037932,68815.672476,-4894.0,2700.5,21229.0,65395.0,479432.0
X15,2399.0,44767.008337,64309.929301,-4894.0,2600.5,19353.0,57462.0,487066.0
X16,2399.0,42248.796165,61074.144569,-4954.0,2266.5,18970.0,54282.5,471145.0
X17,2399.0,41382.323885,60612.288494,-16586.0,1592.0,18260.0,53225.5,469961.0
X18,2399.0,5965.028762,16087.848573,0.0,962.5,2188.0,5194.5,302000.0
X19,2399.0,6433.805752,21003.385961,0.0,698.0,2020.0,5000.0,415552.0
X20,2399.0,4986.984994,13521.889798,0.0,390.0,1900.0,4541.5,202129.0
X21,2399.0,4580.900792,11231.073731,0.0,298.0,1552.0,4500.0,200128.0
X22,2399.0,4904.328053,14482.323214,0.0,326.0,1660.0,4251.5,330982.0
X23,2399.0,5214.233014,18561.122274,0.0,95.5,1500.0,4224.0,527143.0
Y,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
data1.groupby(["Y"]).count()

   Ref.No     X1     X2     X3     X4     X5     X6     X7
Y
0   16766  16766  16766  16766  16766  16766  16766  16766
1    4834   4834   4834   4834   4834   4834   4834   4834

In [91]:
data1.head(10)

   Ref.No      X1  X2  X3  X4  X5  X6  X7  Y
0   22203  320000   2   1   2  27   1   2  1
1    1288  470000   1   2   1  41  -2  -2  0
2   11822   20000   1   2   2  25   1   2  0
3   15085   80000   1   3   1  41   0   0  1
4    6192   30000   1   1   2  30   1  -2  1
5   12894  320000   2   2   1  39   0   0  0
6    2279   50000   2   3   1  37   2   0  1
7    1282  360000   1   1   2  34   1  -2  0
8   13334   50000   2   1   1  25   0   0  0
9   15251   30000   2   2   1  45   2   0  0

In [92]:
data1_feature = data1.drop(labels= "Y" , axis = 1)

In [93]:
data1_feature

       Ref.No      X1  X2  X3  X4  X5  X6  X7
0       22203  320000   2   1   2  27   1   2
1        1288  470000   1   2   1  41  -2  -2
2       11822   20000   1   2   2  25   1   2
3       15085   80000   1   3   1  41   0   0
4        6192   30000   1   1   2  30   1  -2
5       12894  320000   2   2   1  39   0   0
6        2279   50000   2   3   1  37   2   0
7        1282  360000   1   1   2  34   1  -2
8       13334   50000   2   1   1  25   0   0
9       15251   30000   2   2   1  45   2   0
10      12165  130000   2   3   1  41   0   0
11       9895  270000   2   2   1  42   0   0
12      18930  200000   2   1   1  30  -2  -2
13      16828  150000   1   1   1  43  -2  -2
14      16492   50000   1   2   2  22   0   0
15       3785   30000   1   1   2  32   0   0
16      14665   30000   2   2   2  23   0   0
17      18146  260000   1   2   2  31   0   0
18       4376   60000   1   3   1  31   1   2
19      17544   20000   2   2   1  40   0   0
20      18421   40000   2   2   2  24   2   0
21      23940   50000   1   2   2  27   1   2
22       1273  370000   2   1   1  53  -1  -1
23       4811  300000   2   1   2  31   0   0
24       8334  360000   1   1   1  44   0   0
25      15711  270000   1   1   1  45   1  -1
26      16811  140000   1   3   1  38   0   0
27      13816  130000   1   1   2  43   0   0
28      20565   50000   1   3   2  25   0   0
29       9594   20000   2   1   2  26   2   2
...       ...     ...  ..  ..  ..  ..  ..  ..
21570   20745  450000   1   1   1  45  -1  -1
21571    4885   70000   1   2   2  30   0   0
21572    7208  200000   2   2   1  44  -1   2
21573   17977  120000   1   2   1  45   0   0
21574   19881  200000   2   2   2  36   0   0
21575   19480   50000   2   3   2  35   0   0
21576   12381  210000   2   1   2  27   0   0
21577    2342  140000   2   3   2  33   1  -2
21578   12838  150000   2   2   2  23   0   0
21579   18953   70000   2   1   2  26   0   0
21580   14238  500000   1   1   2  41  -1  -1
21581    7306   50000   1   2   3  51   0   0
21582   11652  130000   2   1   2  30   1  -2
21583    3637   50000   1   3   2  30   0   0
21584    2308   30000   2   1   2  30   1  -2
21585    3224   30000   2   2   2  28  -1  -1
21586   22787  100000   2   3   1  40   2   2
21587   17130   80000   2   2   2  24   2   2
21588    4029   60000   2   2   2  27   0   0
21589   23408  360000   2   2   2  35   1  -2
21590    4380  210000   2   1   1  42   1  -2
21591   18482   50000   2   1   1  25   0   0
21592   23587  240000   2   2   1  40  -1  -1
21593   14040   30000   2   2   2  24  -1  -1
21594   20290  210000   2   1   1  51  -1  -1
21595    7650  150000   1   2   1  39  -1  -1
21596   15207   70000   2   3   2  29   0  -1
21597    5471  140000   1   2   2  27   0   0
21598    6855  180000   1   1   1  35   1   2
21599    2673   30000   2   2   2  41   0  -1

[21600 rows x 8 columns]

In [94]:
data1_feature_z = data1_feature.apply(zscore)

In [95]:
data1_feature_z

,Ref.No,X1,X2,X3,X4,X5,X6,X7
0,1.471889,1.199622,0.771310,-1.082964,0.845402,-0.904582,0.890581,1.767277
1,-1.545547,2.362316,-1.296495,0.197247,-1.070322,0.606227,-1.773392,-1.560885
2,-0.025792,-1.125765,-1.296495,0.197247,0.845402,-1.120412,0.890581,1.767277
3,0.444966,-0.660688,-1.296495,1.477459,-1.070322,0.606227,0.002590,0.103196
4,-0.838040,-1.048252,-1.296495,-1.082964,0.845402,-0.580837,0.890581,-1.560885
5,0.128867,1.199622,0.771310,0.197247,-1.070322,0.390397,0.002590,0.103196
6,-1.402574,-0.893226,0.771310,1.477459,-1.070322,0.174567,1.778572,0.103196
7,-1.546412,1.509674,-1.296495,-1.082964,0.845402,-0.149177,0.890581,-1.560885
8,0.192346,-0.893226,0.771310,-1.082964,-1.070322,-1.120412,0.002590,0.103196
9,0.468915,-1.048252,0.771310,0.197247,-1.070322,1.037887,1.778572,0.103196
10,0.023693,-0.273123,0.771310,1.477459,-1.070322,0.606227,0.002590,0.103196
11,-0.303803,0.812058,0.771310,0.197247,-1.070322,0.714142,0.002590,0.103196
12,0.999689,0.269467,0.771310,-1.082964,-1.070322,-0.580837,-1.773392,-1.560885
13,0.696431,-0.118097,-1.296495,-1.082964,-1.070322,0.822057,-1.773392,-1.560885
14,0.647955,-0.893226,-1.296495,0.197247,0.845402,-1.444157,0.002590,0.103196
15,-1.185301,-1.048252,-1.296495,-1.082964,0.845402,-0.365007,0.002590,0.103196
16,0.384372,-1.048252,0.771310,0.197247,0.845402,-1.336242,0.002590,0.103196
17,0.886580,0.734545,-1.296495,0.197247,0.845402,-0.472922,0.002590,0.103196
18,-1.100037,-0.815713,-1.296495,1.477459,-1.070322,-0.472922,0.890581,1.767277
19,0.799729,-1.125765,0.771310,0.197247,-1.070322,0.498312,0.002590,0.103196
20,0.926255,-0.970739,0.771310,0.197247,0.845402,-1.228327,1.778572,0.103196
21,1.722489,-0.893226,-1.296495,0.197247,0.845402,-0.904582,0.890581,1.767277
22,-1.547711,1.587187,0.771310,-1.082964,-1.070322,1.901207,-0.885401,-0.728844
23,-1.037279,1.044596,0.771310,-1.082964,0.845402,-0.472922,0.002590,0.103196
24,-0.529011,1.509674,-1.296495,-1.082964,-1.070322,0.929972,0.002590,0.103196
25,0.535280,0.812058,-1.296495,-1.082964,-1.070322,1.037887,0.890581,-0.728844
26,0.693978,-0.195610,-1.296495,1.477459,-1.070322,0.282482,0.002590,0.103196
27,0.261885,-0.273123,-1.296495,-1.082964,0.845402,0.822057,0.002590,0.103196
28,1.235573,-0.893226,-1.296495,1.477459,0.845402,-1.120412,0.002590,0.103196
29,-0.347229,-1.125765,0.771310,-1.082964,0.845402,-1.012497,1.778572,1.767277
...,...,...,...,...,...,...,...,...
21570,1.261542,2.207290,-1.296495,-1.082964,-1.070322,1.037887,-0.885401,-0.728844
21571,-1.026603,-0.738201,-1.296495,0.197247,0.845402,-0.580837,0.002590,0.103196
21572,-0.691460,0.269467,0.771310,0.197247,-1.070322,0.929972,-0.885401,1.767277
21573,0.862198,-0.350636,-1.296495,0.197247,-1.070322,1.037887,0.002590,0.103196
21574,1.136891,0.269467,0.771310,0.197247,0.845402,0.066652,0.002590,0.103196
21575,1.079038,-0.893226,0.771310,1.477459,0.845402,-0.041262,0.002590,0.103196
21576,0.054856,0.346980,0.771310,-1.082964,0.845402,-0.904582,0.002590,0.103196
21577,-1.393485,-0.195610,0.771310,1.477459,0.845402,-0.257092,0.890581,-1.560885
21578,0.120788,-0.118097,0.771310,0.197247,0.845402,-1.336242,0.002590,0.103196
21579,1.003007,-0.738201,0.771310,-1.082964,0.845402,-1.012497,0.002590,0.103196
21580,0.322768,2.594855,-1.296495,-1.082964,0.845402,0.606227,-0.885401,-0.728844
21581,-0.677322,-0.893226,-1.296495,0.197247,2.761125,1.685377,0.002590,0.103196
21582,-0.050318,-0.273123,0.771310,-1.082964,0.845402,-0.580837,0.890581,-1.560885
21583,-1.206653,-0.893226,-1.296495,1.477459,0.845402,-0.580837,0.002590,0.103196
21584,-1.398390,-1.048252,0.771310,-1.082964,0.845402,-0.580837,0.890581,-1.560885
21585,-1.266237,-1.048252,0.771310,0.197247,0.845402,-0.796667,-0.885401,-0.728844
21586,1.556144,-0.505662,0.771310,1.477459,-1.070322,0.498312,1.778572,1.767277
21587,0.740001,-0.660688,0.771310,0.197247,0.845402,-1.228327,1.778572,1.767277
21588,-1.150099,-0.815713,0.771310,0.197247,0.845402,-0.904582,0.002590,0.103196
21589,1.645736,1.509674,0.771310,0.197247,0.845402,-0.041262,0.890581,-1.560885
21590,-1.099460,0.346980,0.771310,-1.082964,-1.070322,0.714142,0.890581,-1.560885
21591,0.935056,-0.893226,0.771310,-1.082964,-1.070322,-1.120412,0.002590,0.103196
21592,1.671561,0.579519,0.771310,0.197247,-1.070322,0.498312,-0.885401,-0.728844
21593,0.294202,-1.048252,0.771310,0.197247,0.845402,-1.228327,-0.885401,-0.728844
21594,1.195898,0.346980,0.771310,-1.082964,-1.070322,1.685377,-0.885401,-0.728844
21595,-0.627692,-0.118097,-1.296495,0.197247,-1.070322,0.390397,-0.885401,-0.728844
21596,0.462567,-0.738201,0.771310,1.477459,0.845402,-0.688752,0.002590,-0.728844
21597,-0.942060,-0.195610,-1.296495,0.197247,0.845402,-0.904582,0.002590,0.103196
21598,-0.742388,0.114441,-1.296495,-1.082964,-1.070322,-0.041262,0.890581,1.767277
21599,-1.345731,-1.048252,0.771310,0.197247,0.845402,0.606227,0.002590,-0.728844

In [96]:
data2_feature = data2.drop(labels= "Y" , axis = 1)

In [97]:
data2_feature

,Ref.No,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23
0,17083,50000,2,1,2,25,0,0,0,0,...,40002,38008,31898,20154,2000,5040,8034,3029,5000,49436
1,3494,120000,2,2,2,24,0,0,0,0,...,11761,6761,7189,1087,1400,1000,0,1000,1087,801
2,21945,120000,2,2,2,27,1,-2,-1,-1,...,2382,0,0,0,0,2382,0,0,0,0
3,3499,60000,1,1,2,28,0,-1,0,0,...,13421,9900,310,160,6000,10000,900,310,0,3400
4,18973,100000,2,1,2,28,3,2,0,0,...,49899,53407,51951,53195,0,1831,4339,0,2083,1939
5,3249,290000,2,2,1,34,0,0,0,0,...,18231,18593,18986,19967,1292,1303,665,692,1300,636
6,22537,130000,2,2,1,48,2,2,2,2,...,109965,110797,107529,114104,5500,5400,4100,0,8500,0
7,9577,20000,1,2,1,40,1,2,0,0,...,18867,19253,20003,19470,0,1146,532,900,781,0
8,3699,360000,1,2,2,28,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
9,19542,170000,2,1,1,38,-1,-1,-2,-2,...,0,0,0,3001,0,0,0,0,3001,9436
10,15567,50000,1,3,2,40,0,0,0,0,...,46616,48872,19981,16554,2000,4000,4500,2000,1000,3000
11,1962,130000,2,3,2,53,-1,-1,-1,-1,...,27951,17255,10400,18776,45697,27951,17307,10400,18776,2944
12,20610,130000,1,2,2,29,2,2,2,0,...,47113,48218,49408,50648,1600,0,1700,1800,2000,1800
13,22458,50000,2,3,1,49,0,0,0,0,...,29311,27932,28274,27605,3005,2000,2000,2000,1000,2000
14,8683,50000,2,2,2,24,2,2,2,0,...,35917,26946,22458,23569,1700,0,1036,817,1486,3500
15,23712,290000,2,2,1,52,0,0,0,0,...,288983,203517,208435,212674,12880,13000,8000,8600,9000,4000
16,2157,290000,2,1,2,25,0,0,0,0,...,296384,248801,241983,230925,15000,10500,10000,15000,7844,23333
17,17319,120000,2,2,2,25,2,3,3,3,...,100536,103478,104886,107220,5400,5400,5500,4600,4600,5200
18,16160,110000,2,2,2,39,0,0,0,0,...,112974,108390,107180,107309,5500,5900,5500,5000,5000,4300
19,9695,20000,1,3,2,23,2,2,2,2,...,17100,19111,18525,18080,3200,0,2600,0,0,1700
20,14170,300000,1,1,1,40,-1,2,2,-2,...,0,0,0,0,0,0,0,0,0,0
21,6094,20000,1,1,2,24,-1,-1,-1,2,...,679,679,5679,7570,0,679,0,5000,2000,0
22,17252,20000,2,3,1,37,1,2,0,0,...,16429,19764,19140,6420,0,1700,4000,0,1000,0
23,15781,130000,2,1,2,27,0,0,0,0,...,105091,100046,96090,90359,5500,4500,3500,6011,3200,4000
24,4022,270000,2,2,2,31,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
25,7509,10000,2,3,2,51,0,0,0,0,...,5428,7928,6091,0,2134,1000,2500,122,0,0
26,19192,50000,2,2,1,38,0,0,0,-1,...,0,31288,27335,30626,2000,0,95000,1000,3700,16
27,21093,260000,1,5,1,42,0,0,0,0,...,63074,262317,201344,191829,8000,7100,200140,6500,6000,6500
28,9234,140000,1,3,2,30,2,2,2,2,...,136223,113942,109652,109118,6005,210,7903,0,4183,4213
29,9199,260000,1,2,1,31,0,0,0,0,...,7065,0,0,0,4005,4150,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,1136,60000,2,2,2,31,0,0,0,0,...,61017,30117,29526,29201,3200,2535,2331,0,1073,2134
2370,19440,300000,2,2,1,35,0,0,0,0,...,42404,71493,13547,27710,50706,30028,60300,27054,25003,10
2371,19329,140000,2,3,1,40,2,0,0,0,...,32808,35342,35965,36741,1815,1866,3400,1500,1500,1484
2372,4417,270000,2,3,1,37,1,-1,0,0,...,68660,77184,85591,101945,73000,10000,10000,10000,20000,25000
2373,8480,160000,1,2,2,37,1,-2,-2,-2,...,0,0,461,603,0,0,0,461,603,829
2374,16592,80000,1,3,1,31,1,2,0,0,...,26856,27844,27480,28061,0,1459,1447,983,1023,1042
2375,10389,10000,1,2,2,22,0,0,0,0,...,8608,8780,9114,9234,1134,1143,315,476,420,1000
2376,3460,230000,1,2,2,30,0,0,2,0,...,44652,48540,52477,56506,8000,0,4970,4907,4936,5024
2377,12833,110000,1,1,2,26,0,0,0,0,...,111851,153551,75749,77217,5607,4400,2683,5466,5000,2000
2378,17796,470000,2,2,1,54,1,2,0,0,...,358671,367492,374249,381132,0,13033,14800,14359,13897,14425
2379,9860,200000,2,1,1,28,-1,-1,-2,-2,...,0,0,0,0,0,0,0,0,0,0
2380,15638,80000,2,2,2,26,0,0,-1,-1,...,1000,0,0,0,2000,1000,0,0,0,0
2381,19874,500000,2,2,1,46,0,0,2,2,...,185142,115640,78082,80588,19000,5000,0,5000,10000,50000
2382,13735,60000,2,2,1,46,0,0,0,0,...,22388,22431,22324,22601,2000,2000,1000,1000,2000,0
2383,6811,10000,1,1,2,30,0,0,0,0,...,8518,8950,9795,3274,1200,1000,1000,1000,59,0
2384,21393,150000,1,1,1,54,1,2,2,2,...,25294,26780,27143,27563,0,2400,2201,1100,1000,0
2385,19591,80000,2,2,2,36,0,0,0,0,...,53599,52038,53175,55751,10000,24369,2500,2500,5000,2700
2386,12408,270000,2,1,1,33,0,0,0,-2,...,0,0,4448,5667,5000,0,0,4448,1300,2443
2387,11468,20000,1,3,1,45,-1,2,0,0,...,1560,1170,780,780,0,1000,0,0,0,0
2388,1810,500000,2,1,2,46,-2,-1,-1,-1,...,60560,104734,41018,6258,163500,70160,104734,41018,6258,70356
2389,12288,200000,1,1,1,40,-1,-1,-1,-2,...,0,0,990,0,454,0,0,990,0,0
2390,21128,500000,1,1,1,41,-1,-1,2,2,...,390,0,3280,2500,780,0,0,3280,0,0
2391,28,50000,2,3,2,30,0,0,0,0,...,17163,17878,18931,19617,1300,1300,1000,1500,1000,1012
2392,10518,280000,2,3,1,37,-1,-1,2,-1,...,15287,14201,26133,4504,38979,16,14201,26133,4504,10748
2393,7060,50000,2,2,3,30,2,2,0,0,...,34519,33965,33273,31960,0,1466,1282,1293,1257,3013
2394,14580,140000,2,2,1,34,0,0,0,0,...,18226,19915,20891,21542,2500,1500,2000,1300,1000,1500
2395,5172,70000,1,3,1,46,2,2,2,2,...,32855,33316,34137,33439,2352,2531,1300,1500,0,1400
2396,3598,50000,2,2,1,37,2,2,2,0,...,38222,13026,13268,13497,5500,0,580,600,600,600
2397,18841,190000,2,2,2,27,2,2,2,2,...,5459,6214,7104,8973,1000,1000,1000,1000,2000,2000
2398,21365,70000,1,2,1,54,-1,0,0,0,...,22437,23448,23914,24415,1351,1378,1389,855,885,1132

In [98]:
data2_feature_z = data2_feature.apply(zscore)

In [99]:
data2_feature_z

,Ref.No,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23
0,0.737328,-0.905841,0.750244,-1.119057,0.872660,-1.113037,0.004933,0.099271,0.109695,0.160042,...,-0.130507,-0.105122,-0.169515,-0.350304,-0.246512,-0.066375,0.225386,-0.138208,0.006607,2.382991
1,-1.232127,-0.367961,0.750244,0.180371,0.872660,-1.220432,0.004933,0.099271,0.109695,0.160042,...,-0.540978,-0.591105,-0.574173,-0.664943,-0.283815,-0.258765,-0.368885,-0.318905,-0.263640,-0.237817
2,1.441978,-0.367961,0.750244,0.180371,0.872660,-0.898246,0.915257,-1.583783,-0.720455,-0.691267,...,-0.677299,-0.696259,-0.691907,-0.682881,-0.370856,-0.192952,-0.368885,-0.407962,-0.338713,-0.280981
3,-1.231402,-0.829001,-1.332899,-1.119057,0.872660,-0.790850,0.004933,-0.742256,0.109695,0.160042,...,-0.516851,-0.542284,-0.686830,-0.680240,0.002174,0.169827,-0.302313,-0.380355,-0.338713,-0.097764
4,1.011246,-0.521641,0.750244,-1.119057,0.872660,-0.790850,2.735906,1.782325,0.109695,0.160042,...,0.013342,0.134377,0.158893,0.194930,-0.370856,-0.219192,-0.047931,-0.407962,-0.194852,-0.176493
5,-1.267635,0.938320,0.750244,0.180371,-1.040970,-0.146477,0.004933,0.099271,0.109695,0.160042,...,-0.446940,-0.407083,-0.380974,-0.353390,-0.290530,-0.244336,-0.319695,-0.346335,-0.248930,-0.246709
6,1.527777,-0.291121,0.750244,0.180371,-1.040970,1.357061,1.825582,1.782325,1.769993,1.862659,...,0.886378,1.026961,1.069091,1.200035,-0.028912,-0.049231,-0.065610,-0.407962,0.248332,-0.280981
7,-0.350517,-1.136361,-1.332899,0.180371,-1.040970,0.497896,0.915257,1.782325,0.109695,0.160042,...,-0.437696,-0.396818,-0.364318,-0.361592,-0.370856,-0.251812,-0.329533,-0.327811,-0.284774,-0.280981
8,-1.202416,1.476200,-1.332899,0.180371,0.872660,-0.790850,0.915257,-1.583783,-1.550604,-1.542576,...,-0.711920,-0.696259,-0.691907,-0.682881,-0.370856,-0.306386,-0.368885,-0.407962,-0.338713,-0.280981
9,1.093711,0.016239,0.750244,-1.119057,-1.040970,0.283105,-0.905391,-0.742256,-1.550604,-1.542576,...,-0.711920,-0.696259,-0.691907,-0.633359,-0.370856,-0.306386,-0.368885,-0.407962,-0.131452,0.227500
10,0.517614,-0.905841,-1.332899,1.479799,0.872660,0.497896,0.004933,0.099271,0.109695,0.160042,...,-0.034375,0.063845,-0.364679,-0.409711,-0.246512,-0.115901,-0.036022,-0.229848,-0.269649,-0.119319
11,-1.454160,-0.291121,0.750244,1.479799,0.872660,1.894038,-0.905391,-0.742256,-0.720455,-0.691267,...,-0.305663,-0.427893,-0.521586,-0.373044,2.470203,1.024677,0.911306,0.518233,0.958034,-0.122337
12,1.248496,-0.291121,-1.332899,0.180371,0.872660,-0.683455,1.825582,1.782325,1.769993,0.160042,...,-0.027151,0.053673,0.117246,0.152900,-0.271381,-0.306386,-0.243137,-0.247659,-0.200585,-0.183984
13,1.516327,-0.905841,0.750244,1.479799,-1.040970,1.464456,0.004933,0.099271,0.109695,0.160042,...,-0.285896,-0.261834,-0.228865,-0.227350,-0.184030,-0.211144,-0.220946,-0.229848,-0.269649,-0.173206
14,-0.480085,-0.905841,0.750244,0.180371,0.872660,-1.220432,1.825582,1.782325,1.769993,0.160042,...,-0.189881,-0.277169,-0.324113,-0.293951,-0.265164,-0.306386,-0.292253,-0.335203,-0.236084,-0.092375
15,1.698070,0.938320,0.750244,0.180371,-1.040970,1.786643,0.004933,0.099271,0.109695,0.160042,...,3.488333,2.469029,2.721624,2.826611,0.429915,0.312691,0.222871,0.357930,0.282864,-0.065432
16,-1.425899,0.938320,0.750244,-1.119057,0.872660,-1.113037,0.004933,0.099271,0.109695,0.160042,...,3.595904,3.173328,3.271038,3.127785,0.561719,0.193637,0.370811,0.927896,0.203026,0.976371
17,0.771532,-0.367961,0.750244,0.180371,0.872660,-1.113037,1.825582,2.623852,2.600142,2.713968,...,0.749331,0.913129,1.025807,1.086436,-0.035129,-0.049231,0.037948,0.001701,-0.021018,-0.000767
18,0.603558,-0.444801,0.750244,0.180371,0.872660,0.390501,0.004933,0.099271,0.109695,0.160042,...,0.930112,0.989525,1.063375,1.087905,-0.028912,-0.025421,0.037948,0.037324,0.006607,-0.049266
19,-0.333416,-1.136361,-1.332899,1.479799,0.872660,-1.327828,1.825582,1.782325,1.769993,1.862659,...,-0.463378,-0.399026,-0.388524,-0.384529,-0.171906,-0.306386,-0.176564,-0.407962,-0.338713,-0.189372
20,0.315147,1.015160,-1.332899,-1.119057,-1.040970,0.497896,-0.905391,1.782325,1.769993,-1.542576,...,-0.711920,-0.696259,-0.691907,-0.682881,-0.370856,-0.306386,-0.368885,-0.407962,-0.338713,-0.280981
21,-0.855309,-1.136361,-1.332899,-1.119057,0.872660,-1.220432,-0.905391,-0.742256,-0.720455,1.862659,...,-0.702051,-0.685698,-0.598902,-0.557962,-0.370856,-0.274051,-0.368885,0.037324,-0.200585,-0.280981
22,0.761821,-1.136361,0.750244,1.479799,-1.040970,0.175710,0.915257,1.782325,0.109695,0.160042,...,-0.473131,-0.388870,-0.378452,-0.576939,-0.370856,-0.225430,-0.073007,-0.407962,-0.269649,-0.280981
23,0.548629,-0.291121,0.750244,-1.119057,0.872660,-0.898246,0.004933,0.099271,0.109695,0.160042,...,0.815536,0.859751,0.881755,0.808201,-0.028912,-0.092090,-0.109992,0.127361,-0.117708,-0.065432
24,-1.155604,0.784640,0.750244,0.180371,0.872660,-0.468664,-1.815716,-1.583783,-1.550604,-1.542576,...,-0.711920,-0.696259,-0.691907,-0.682881,-0.370856,-0.306386,-0.368885,-0.407962,-0.338713,-0.280981
25,-0.650233,-1.213201,0.750244,1.479799,0.872660,1.679247,0.004933,0.099271,0.109695,0.160042,...,-0.633026,-0.572955,-0.592155,-0.682881,-0.238181,-0.258765,-0.183961,-0.397097,-0.338713,-0.280981
26,1.042986,-0.905841,0.750244,0.180371,-1.040970,0.283105,0.004933,0.099271,0.109695,-0.691267,...,-0.711920,-0.209638,-0.244243,-0.177498,-0.246512,-0.306386,6.658225,-0.318905,-0.083176,-0.280119
27,1.318498,0.707799,-1.332899,4.078654,-1.040970,0.712687,0.004933,0.099271,0.109695,0.160042,...,0.204836,3.383542,2.605495,2.482633,0.126518,0.031725,14.435386,0.170910,0.075672,0.069286
28,-0.400228,-0.214281,-1.332899,1.479799,0.872660,-0.576059,1.825582,1.782325,1.769993,1.862659,...,1.268027,1.075875,1.103859,1.117757,0.002485,-0.296386,0.215696,-0.407962,-0.049818,-0.053954
29,-0.405301,0.707799,-1.332899,0.180371,-1.040970,-0.468664,0.004933,0.099271,0.109695,0.160042,...,-0.609233,-0.696259,-0.691907,-0.682881,-0.121858,-0.108758,-0.368885,-0.407962,-0.338713,-0.280981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,-1.573872,-0.829001,0.750244,0.180371,0.872660,-0.468664,0.004933,0.099271,0.109695,0.160042,...,0.174938,-0.227851,-0.208361,-0.201013,-0.171906,-0.185666,-0.196462,-0.407962,-0.264607,-0.165985
2370,1.078928,1.015160,0.750244,0.180371,-1.040970,-0.039081,0.004933,0.099271,0.109695,0.160042,...,-0.095595,0.415668,-0.470048,-0.225617,2.781621,1.123586,4.091480,2.001392,1.388097,-0.280442
2371,1.062841,-0.214281,0.750244,1.479799,-1.040970,0.497896,1.825582,0.099271,0.109695,0.160042,...,-0.235069,-0.146587,-0.102909,-0.076590,-0.258014,-0.217525,-0.117389,-0.274377,-0.235117,-0.201012
2372,-1.098357,0.784640,0.750244,1.479799,-1.040970,0.175710,0.915257,-0.742256,0.109695,0.160042,...,0.286026,0.504180,0.709813,0.999390,4.167676,0.169827,0.370811,0.482610,1.042569,1.066201
2373,-0.509506,-0.060601,-1.332899,0.180371,0.872660,0.175710,0.915257,-1.583783,-1.550604,-1.542576,...,-0.711920,-0.696259,-0.684357,-0.672930,-0.370856,-0.306386,-0.368885,-0.366907,-0.297067,-0.236308
2374,0.666167,-0.675321,-1.332899,1.479799,-1.040970,-0.468664,0.915257,1.782325,0.109695,0.160042,...,-0.321579,-0.263203,-0.241868,-0.219825,-0.370856,-0.236907,-0.261851,-0.320419,-0.268060,-0.224830
2375,-0.232834,-1.213201,-1.332899,0.180371,0.872660,-1.435223,0.004933,0.099271,0.109695,0.160042,...,-0.586806,-0.559704,-0.542647,-0.530503,-0.300353,-0.251955,-0.345585,-0.365571,-0.309706,-0.227094
2376,-1.237055,0.477279,-1.332899,0.180371,0.872660,-0.576059,0.004933,0.099271,1.769993,0.160042,...,-0.062921,0.058681,0.167507,0.249567,0.126518,-0.306386,-0.001256,0.029041,0.002187,-0.010251
2377,0.121375,-0.444801,-1.332899,-1.119057,0.872660,-1.005641,0.004933,0.099271,0.109695,0.160042,...,0.913790,1.691911,0.548631,0.591335,-0.022259,-0.096852,-0.170425,0.078824,0.006607,-0.173206
2378,0.840663,2.321440,0.750244,0.180371,-1.040970,2.001434,0.915257,1.782325,0.109695,0.160042,...,4.501221,5.019322,5.437152,5.606462,-0.370856,0.314262,0.725865,0.870811,0.621071,0.496343
2379,-0.309502,0.246759,0.750244,-1.119057,-1.040970,-0.790850,-0.905391,-0.742256,-1.550604,-1.542576,...,-0.711920,-0.696259,-0.691907,-0.682881,-0.370856,-0.306386,-0.368885,-0.407962,-0.338713,-0.280981
2380,0.527904,-0.675321,0.750244,0.180371,0.872660,-1.005641,0.004933,0.099271,-0.720455,-0.691267,...,-0.697385,-0.696259,-0.691907,-0.682881,-0.246512,-0.258765,-0.368885,-0.407962,-0.338713,-0.280981
2381,1.141828,2.551960,0.750244,0.180371,-1.040970,1.142270,0.004933,0.099271,1.769993,1.862659,...,1.979046,1.102283,0.586839,0.646962,0.810406,-0.068280,-0.368885,0.037324,0.351928,2.413383
2382,0.252102,-0.829001,0.750244,0.180371,-1.040970,1.142270,0.004933,0.099271,0.109695,0.160042,...,-0.386519,-0.347391,-0.326307,-0.309925,-0.246512,-0.211144,-0.294916,-0.318905,-0.200585,-0.280981
2383,-0.751394,-1.213201,-1.332899,-1.119057,0.872660,-0.576059,0.004933,0.099271,0.109695,0.160042,...,-0.588114,-0.557060,-0.531494,-0.628854,-0.296250,-0.258765,-0.294916,-0.318905,-0.334638,-0.280981
2384,1.361977,-0.137441,-1.332899,-1.119057,-1.040970,2.001434,0.915257,1.782325,1.769993,1.862659,...,-0.344282,-0.279751,-0.247387,-0.228043,-0.370856,-0.192095,-0.206078,-0.309999,-0.269649,-0.280981
2385,1.100813,-0.675321,0.750244,0.180371,0.872660,0.068314,0.004933,0.099271,0.109695,0.160042,...,0.067120,0.113085,0.178938,0.237108,0.250861,0.854097,-0.183961,-0.185319,0.006607,-0.135485
2386,0.059780,0.784640,0.750244,-1.119057,-1.040970,-0.253873,0.004933,0.099271,0.109695,-1.542576,...,-0.711920,-0.696259,-0.619062,-0.589365,-0.059997,-0.306386,-0.368885,-0.011836,-0.248930,-0.149334
2387,-0.076454,-1.136361,-1.332899,1.479799,-1.040970,1.034874,-0.905391,1.782325,0.109695,0.160042,...,-0.689246,-0.678062,-0.679133,-0.670009,-0.370856,-0.258765,-0.368885,-0.407962,-0.338713,-0.280981
2388,-1.476189,2.551960,0.750244,-1.119057,0.872660,1.142270,-1.815716,-0.742256,-0.720455,-0.691267,...,0.168296,0.932663,-0.020157,-0.579613,9.794213,3.034724,7.378245,3.244988,0.093490,3.510313
2389,0.042388,0.246759,-1.332899,-1.119057,-1.040970,0.497896,-0.905391,-0.742256,-0.720455,-1.542576,...,-0.711920,-0.696259,-0.675693,-0.682881,-0.342630,-0.306386,-0.368885,-0.319796,-0.338713,-0.280981
2390,1.323570,2.551960,-1.332899,-1.119057,-1.040970,0.605292,-0.905391,-0.742256,1.769993,1.862659,...,-0.706251,-0.696259,-0.638190,-0.641626,-0.322362,-0.306386,-0.368885,-0.115855,-0.338713,-0.280981
2391,-1.734455,-0.905841,0.750244,1.479799,0.872660,-0.576059,0.004933,0.099271,0.109695,0.160042,...,-0.462463,-0.418203,-0.381874,-0.359166,-0.290033,-0.244478,-0.294916,-0.274377,-0.269649,-0.226447
2392,-0.214138,0.861480,0.750244,1.479799,-1.040970,0.175710,-0.905391,-0.742256,1.769993,-0.691267,...,-0.489729,-0.475391,-0.263928,-0.608557,2.052534,-0.305624,0.681557,1.919371,-0.027648,0.298200
2393,-0.715306,-0.905841,0.750244,0.180371,2.786289,-0.576059,1.825582,1.782325,0.109695,0.160042,...,-0.210200,-0.168003,-0.146996,-0.155485,-0.370856,-0.236573,-0.274056,-0.292811,-0.251899,-0.118618
2394,0.374568,-0.214281,0.750244,0.180371,-1.040970,-0.146477,0.004933,0.099271,0.109695,0.160042,...,-0.447012,-0.386522,-0.349776,-0.327400,-0.215427,-0.234954,-0.220946,-0.292188,-0.269649,-0.200150
2395,-0.988934,-0.752161,-1.332899,1.479799,-1.040970,1.142270,1.825582,1.782325,1.769993,1.862659,...,-0.234386,-0.178097,-0.132847,-0.131079,-0.224628,-0.185857,-0.272725,-0.274377,-0.338713,-0.205539
2396,-1.217054,-0.905841,0.750244,0.180371,-1.040970,0.175710,1.825582,1.782325,1.769993,0.160042,...,-0.156378,-0.493666,-0.474617,-0.460156,-0.028912,-0.306386,-0.325983,-0.354528,-0.297275,-0.248648
2397,0.992115,0.169919,0.750244,0.180371,0.872660,-0.898246,1.825582,1.782325,1.769993,1.862659,...,-0.632576,-0.599613,-0.575565,-0.534810,-0.308684,-0.258765,-0.294916,-0.318905,-0.200585,-0.173206
2398,1.357919,-0.752161,-1.332899,0.180371,-1.040970,2.001434,-0.905391,0.099271,0.109695,0.160042,...,-0.385807,-0.331573,-0.300268,-0.279990,-0.286862,-0.240764,-0.266141,-0.331818,-0.277591,-0.219980

In [100]:
data1_labels = data1["Y"]

In [101]:
data1_labels

0        1
1        0
2        0
3        1
4        1
5        0
6        1
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       1
19       0
20       1
21       1
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       1
        ..
21570    1
21571    1
21572    0
21573    0
21574    1
21575    0
21576    0
21577    0
21578    0
21579    0
21580    1
21581    0
21582    0
21583    0
21584    0
21585    1
21586    1
21587    1
21588    0
21589    0
21590    0
21591    1
21592    1
21593    0
21594    0
21595    0
21596    0
21597    0
21598    1
21599    0
Name: Y, Length: 21600, dtype: int64

In [102]:
data2_labels = data2["Y"]

In [103]:
data2_labels

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15     NaN
16     NaN
17     NaN
18     NaN
19     NaN
20     NaN
21     NaN
22     NaN
23     NaN
24     NaN
25     NaN
26     NaN
27     NaN
28     NaN
29     NaN
        ..
2369   NaN
2370   NaN
2371   NaN
2372   NaN
2373   NaN
2374   NaN
2375   NaN
2376   NaN
2377   NaN
2378   NaN
2379   NaN
2380   NaN
2381   NaN
2382   NaN
2383   NaN
2384   NaN
2385   NaN
2386   NaN
2387   NaN
2388   NaN
2389   NaN
2390   NaN
2391   NaN
2392   NaN
2393   NaN
2394   NaN
2395   NaN
2396   NaN
2397   NaN
2398   NaN
Name: Y, Length: 2399, dtype: float64

In [104]:
X1 = np.array(data1_feature_z)

In [105]:
x!

SyntaxError: invalid syntax (<ipython-input-105-e3ef757ecb7f>, line 1)

In [106]:
x1

NameError: name 'x1' is not defined

In [107]:
X1

array([[ 1.47188938,  1.19962219,  0.7713105 , ..., -0.9045823 ,
         0.89058091,  1.76727727],
       [-1.54554677,  2.36231583, -1.29649473, ...,  0.60622736,
        -1.7733919 , -1.56088499],
       [-0.02579194, -1.12576508, -1.29649473, ..., -1.12041225,
         0.89058091,  1.76727727],
       ...,
       [-0.94205954, -0.19561017, -1.29649473, ..., -0.9045823 ,
         0.00258997,  0.10319614],
       [-0.74238794,  0.11444147, -1.29649473, ..., -0.04126249,
         0.89058091,  1.76727727],
       [-1.3457309 , -1.04825217,  0.7713105 , ...,  0.60622736,
         0.00258997, -0.72884442]])

In [108]:
Y1 = np.array(data1_labels)

In [109]:
Y1

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [114]:
X_Train = X1
Y_Train = Y1
X_Test = data_test
Y_Test = data2_labels

In [115]:
X_Train.shape, Y_Train.shape, X_Test.shape, Y_Test.shape

((21600, 8), (21600,), (2399, 8), (2399,))

In [116]:
from sklearn.tree import DecisionTreeClassifier

# Call Decision Tree Classifier algorithm again and predict
DTClassifier_new = DecisionTreeClassifier (max_depth=3, random_state = 0)
DTClassifier_new.fit(X_Train, Y_Train)
predicted_labels = DTClassifier_new.predict(X_Test)
print(predicted_labels)
#accuracy_score_new = accuracy_score(Y_Test, predicted_labels)
#print(accuracy_score_new)

[0 0 0 ... 1 1 0]

In [119]:
from sklearn.tree import DecisionTreeClassifier

# Call Decision Tree Classifier algorithm again and predict
DTClassifier_new = DecisionTreeClassifier (max_depth=6, random_state = 0)
DTClassifier_new.fit(X_Train, Y_Train)
predicted_labels = DTClassifier_new.predict(X_Test)
print(predicted_labels)
#accuracy_score_new = accuracy_score(Y_Test, predicted_labels)
#print(accuracy_score_new)

[0 0 0 ... 1 1 0]

In [121]:
sub = pd.DataFrame(pd.read_csv("test.csv")['Ref.No'])
sub['Y'] = predicted_labels
sub.to_csv("citibank_submission.csv", index = False)